version: '3'

services:
  wordpress:
    build: .
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      #UPLOADS_INI_URL: ${UPLOADS_INI_URL}
      #WP_CONFIG_PHP_URL: ${WP_CONFIG_PHP_URL}
      #HTACCESS_URL: ${HTACCESS_URL}
      #INDEX_PHP_URL: ${INDEX_PHP_URL}
      #PHP_INI_URL: ${PHP_INI_URL}
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: